// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train_serving.proto

package wt;

public final class TrainServing {
  private TrainServing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PredictRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wt.PredictRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float feature = 1;</code>
     */
    java.util.List<java.lang.Float> getFeatureList();
    /**
     * <code>repeated float feature = 1;</code>
     */
    int getFeatureCount();
    /**
     * <code>repeated float feature = 1;</code>
     */
    float getFeature(int index);

    /**
     * <code>int32 sample_size = 2;</code>
     */
    int getSampleSize();

    /**
     * <code>string model_name = 3;</code>
     */
    java.lang.String getModelName();
    /**
     * <code>string model_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getModelNameBytes();
  }
  /**
   * Protobuf type {@code wt.PredictRequest}
   */
  public  static final class PredictRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wt.PredictRequest)
      PredictRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PredictRequest.newBuilder() to construct.
    private PredictRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PredictRequest() {
      feature_ = emptyFloatList();
      modelName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PredictRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PredictRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                feature_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              feature_.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                feature_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                feature_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {

              sampleSize_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              modelName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          feature_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wt.TrainServing.internal_static_wt_PredictRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wt.TrainServing.internal_static_wt_PredictRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wt.TrainServing.PredictRequest.class, wt.TrainServing.PredictRequest.Builder.class);
    }

    public static final int FEATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList feature_;
    /**
     * <code>repeated float feature = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getFeatureList() {
      return feature_;
    }
    /**
     * <code>repeated float feature = 1;</code>
     */
    public int getFeatureCount() {
      return feature_.size();
    }
    /**
     * <code>repeated float feature = 1;</code>
     */
    public float getFeature(int index) {
      return feature_.getFloat(index);
    }
    private int featureMemoizedSerializedSize = -1;

    public static final int SAMPLE_SIZE_FIELD_NUMBER = 2;
    private int sampleSize_;
    /**
     * <code>int32 sample_size = 2;</code>
     */
    public int getSampleSize() {
      return sampleSize_;
    }

    public static final int MODEL_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object modelName_;
    /**
     * <code>string model_name = 3;</code>
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      }
    }
    /**
     * <code>string model_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getFeatureList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(featureMemoizedSerializedSize);
      }
      for (int i = 0; i < feature_.size(); i++) {
        output.writeFloatNoTag(feature_.getFloat(i));
      }
      if (sampleSize_ != 0) {
        output.writeInt32(2, sampleSize_);
      }
      if (!getModelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, modelName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getFeatureList().size();
        size += dataSize;
        if (!getFeatureList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        featureMemoizedSerializedSize = dataSize;
      }
      if (sampleSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sampleSize_);
      }
      if (!getModelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, modelName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wt.TrainServing.PredictRequest)) {
        return super.equals(obj);
      }
      wt.TrainServing.PredictRequest other = (wt.TrainServing.PredictRequest) obj;

      if (!getFeatureList()
          .equals(other.getFeatureList())) return false;
      if (getSampleSize()
          != other.getSampleSize()) return false;
      if (!getModelName()
          .equals(other.getModelName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFeatureCount() > 0) {
        hash = (37 * hash) + FEATURE_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureList().hashCode();
      }
      hash = (37 * hash) + SAMPLE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSampleSize();
      hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getModelName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wt.TrainServing.PredictRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.PredictRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wt.TrainServing.PredictRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wt.PredictRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wt.PredictRequest)
        wt.TrainServing.PredictRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wt.TrainServing.internal_static_wt_PredictRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wt.TrainServing.internal_static_wt_PredictRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wt.TrainServing.PredictRequest.class, wt.TrainServing.PredictRequest.Builder.class);
      }

      // Construct using wt.TrainServing.PredictRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        feature_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleSize_ = 0;

        modelName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wt.TrainServing.internal_static_wt_PredictRequest_descriptor;
      }

      @java.lang.Override
      public wt.TrainServing.PredictRequest getDefaultInstanceForType() {
        return wt.TrainServing.PredictRequest.getDefaultInstance();
      }

      @java.lang.Override
      public wt.TrainServing.PredictRequest build() {
        wt.TrainServing.PredictRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wt.TrainServing.PredictRequest buildPartial() {
        wt.TrainServing.PredictRequest result = new wt.TrainServing.PredictRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          feature_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.feature_ = feature_;
        result.sampleSize_ = sampleSize_;
        result.modelName_ = modelName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wt.TrainServing.PredictRequest) {
          return mergeFrom((wt.TrainServing.PredictRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wt.TrainServing.PredictRequest other) {
        if (other == wt.TrainServing.PredictRequest.getDefaultInstance()) return this;
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
        if (other.getSampleSize() != 0) {
          setSampleSize(other.getSampleSize());
        }
        if (!other.getModelName().isEmpty()) {
          modelName_ = other.modelName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wt.TrainServing.PredictRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wt.TrainServing.PredictRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList feature_ = emptyFloatList();
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          feature_ = mutableCopy(feature_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getFeatureList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(feature_) : feature_;
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public int getFeatureCount() {
        return feature_.size();
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public float getFeature(int index) {
        return feature_.getFloat(index);
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public Builder setFeature(
          int index, float value) {
        ensureFeatureIsMutable();
        feature_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public Builder addFeature(float value) {
        ensureFeatureIsMutable();
        feature_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public Builder addAllFeature(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFeatureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feature_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float feature = 1;</code>
       */
      public Builder clearFeature() {
        feature_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int sampleSize_ ;
      /**
       * <code>int32 sample_size = 2;</code>
       */
      public int getSampleSize() {
        return sampleSize_;
      }
      /**
       * <code>int32 sample_size = 2;</code>
       */
      public Builder setSampleSize(int value) {
        
        sampleSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sample_size = 2;</code>
       */
      public Builder clearSampleSize() {
        
        sampleSize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modelName_ = "";
      /**
       * <code>string model_name = 3;</code>
       */
      public java.lang.String getModelName() {
        java.lang.Object ref = modelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          modelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getModelNameBytes() {
        java.lang.Object ref = modelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model_name = 3;</code>
       */
      public Builder setModelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model_name = 3;</code>
       */
      public Builder clearModelName() {
        
        modelName_ = getDefaultInstance().getModelName();
        onChanged();
        return this;
      }
      /**
       * <code>string model_name = 3;</code>
       */
      public Builder setModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modelName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wt.PredictRequest)
    }

    // @@protoc_insertion_point(class_scope:wt.PredictRequest)
    private static final wt.TrainServing.PredictRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wt.TrainServing.PredictRequest();
    }

    public static wt.TrainServing.PredictRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictRequest>
        PARSER = new com.google.protobuf.AbstractParser<PredictRequest>() {
      @java.lang.Override
      public PredictRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PredictRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PredictRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PredictRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wt.TrainServing.PredictRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PredictReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wt.PredictReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float result = 1;</code>
     */
    java.util.List<java.lang.Float> getResultList();
    /**
     * <code>repeated float result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated float result = 1;</code>
     */
    float getResult(int index);
  }
  /**
   * Protobuf type {@code wt.PredictReply}
   */
  public  static final class PredictReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wt.PredictReply)
      PredictReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PredictReply.newBuilder() to construct.
    private PredictReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PredictReply() {
      result_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PredictReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PredictReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                result_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                result_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                result_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          result_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wt.TrainServing.internal_static_wt_PredictReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wt.TrainServing.internal_static_wt_PredictReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wt.TrainServing.PredictReply.class, wt.TrainServing.PredictReply.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList result_;
    /**
     * <code>repeated float result = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getResultList() {
      return result_;
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public float getResult(int index) {
      return result_.getFloat(index);
    }
    private int resultMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getResultList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(resultMemoizedSerializedSize);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeFloatNoTag(result_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getResultList().size();
        size += dataSize;
        if (!getResultList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        resultMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wt.TrainServing.PredictReply)) {
        return super.equals(obj);
      }
      wt.TrainServing.PredictReply other = (wt.TrainServing.PredictReply) obj;

      if (!getResultList()
          .equals(other.getResultList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wt.TrainServing.PredictReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.PredictReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.PredictReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.PredictReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wt.TrainServing.PredictReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wt.PredictReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wt.PredictReply)
        wt.TrainServing.PredictReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wt.TrainServing.internal_static_wt_PredictReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wt.TrainServing.internal_static_wt_PredictReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wt.TrainServing.PredictReply.class, wt.TrainServing.PredictReply.Builder.class);
      }

      // Construct using wt.TrainServing.PredictReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wt.TrainServing.internal_static_wt_PredictReply_descriptor;
      }

      @java.lang.Override
      public wt.TrainServing.PredictReply getDefaultInstanceForType() {
        return wt.TrainServing.PredictReply.getDefaultInstance();
      }

      @java.lang.Override
      public wt.TrainServing.PredictReply build() {
        wt.TrainServing.PredictReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wt.TrainServing.PredictReply buildPartial() {
        wt.TrainServing.PredictReply result = new wt.TrainServing.PredictReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          result_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wt.TrainServing.PredictReply) {
          return mergeFrom((wt.TrainServing.PredictReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wt.TrainServing.PredictReply other) {
        if (other == wt.TrainServing.PredictReply.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wt.TrainServing.PredictReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wt.TrainServing.PredictReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList result_ = emptyFloatList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          result_ = mutableCopy(result_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getResultList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(result_) : result_;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public int getResultCount() {
        return result_.size();
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public float getResult(int index) {
        return result_.getFloat(index);
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder setResult(
          int index, float value) {
        ensureResultIsMutable();
        result_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addResult(float value) {
        ensureResultIsMutable();
        result_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder clearResult() {
        result_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wt.PredictReply)
    }

    // @@protoc_insertion_point(class_scope:wt.PredictReply)
    private static final wt.TrainServing.PredictReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wt.TrainServing.PredictReply();
    }

    public static wt.TrainServing.PredictReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictReply>
        PARSER = new com.google.protobuf.AbstractParser<PredictReply>() {
      @java.lang.Override
      public PredictReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PredictReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PredictReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PredictReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wt.TrainServing.PredictReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wt.TrainRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float x = 1;</code>
     */
    java.util.List<java.lang.Float> getXList();
    /**
     * <code>repeated float x = 1;</code>
     */
    int getXCount();
    /**
     * <code>repeated float x = 1;</code>
     */
    float getX(int index);

    /**
     * <code>repeated float y = 2;</code>
     */
    java.util.List<java.lang.Float> getYList();
    /**
     * <code>repeated float y = 2;</code>
     */
    int getYCount();
    /**
     * <code>repeated float y = 2;</code>
     */
    float getY(int index);

    /**
     * <code>int32 batch_size = 3;</code>
     */
    int getBatchSize();

    /**
     * <code>string model_name = 4;</code>
     */
    java.lang.String getModelName();
    /**
     * <code>string model_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getModelNameBytes();
  }
  /**
   * Protobuf type {@code wt.TrainRequest}
   */
  public  static final class TrainRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wt.TrainRequest)
      TrainRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrainRequest.newBuilder() to construct.
    private TrainRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrainRequest() {
      x_ = emptyFloatList();
      y_ = emptyFloatList();
      modelName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TrainRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrainRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                x_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              x_.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                x_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                x_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                y_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              y_.addFloat(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                y_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                y_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              batchSize_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              modelName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          x_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          y_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wt.TrainServing.internal_static_wt_TrainRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wt.TrainServing.internal_static_wt_TrainRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wt.TrainServing.TrainRequest.class, wt.TrainServing.TrainRequest.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList x_;
    /**
     * <code>repeated float x = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getXList() {
      return x_;
    }
    /**
     * <code>repeated float x = 1;</code>
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <code>repeated float x = 1;</code>
     */
    public float getX(int index) {
      return x_.getFloat(index);
    }
    private int xMemoizedSerializedSize = -1;

    public static final int Y_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.FloatList y_;
    /**
     * <code>repeated float y = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getYList() {
      return y_;
    }
    /**
     * <code>repeated float y = 2;</code>
     */
    public int getYCount() {
      return y_.size();
    }
    /**
     * <code>repeated float y = 2;</code>
     */
    public float getY(int index) {
      return y_.getFloat(index);
    }
    private int yMemoizedSerializedSize = -1;

    public static final int BATCH_SIZE_FIELD_NUMBER = 3;
    private int batchSize_;
    /**
     * <code>int32 batch_size = 3;</code>
     */
    public int getBatchSize() {
      return batchSize_;
    }

    public static final int MODEL_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object modelName_;
    /**
     * <code>string model_name = 4;</code>
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      }
    }
    /**
     * <code>string model_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getXList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(xMemoizedSerializedSize);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeFloatNoTag(x_.getFloat(i));
      }
      if (getYList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(yMemoizedSerializedSize);
      }
      for (int i = 0; i < y_.size(); i++) {
        output.writeFloatNoTag(y_.getFloat(i));
      }
      if (batchSize_ != 0) {
        output.writeInt32(3, batchSize_);
      }
      if (!getModelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, modelName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getXList().size();
        size += dataSize;
        if (!getXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getYList().size();
        size += dataSize;
        if (!getYList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        yMemoizedSerializedSize = dataSize;
      }
      if (batchSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, batchSize_);
      }
      if (!getModelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, modelName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wt.TrainServing.TrainRequest)) {
        return super.equals(obj);
      }
      wt.TrainServing.TrainRequest other = (wt.TrainServing.TrainRequest) obj;

      if (!getXList()
          .equals(other.getXList())) return false;
      if (!getYList()
          .equals(other.getYList())) return false;
      if (getBatchSize()
          != other.getBatchSize()) return false;
      if (!getModelName()
          .equals(other.getModelName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getXCount() > 0) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getXList().hashCode();
      }
      if (getYCount() > 0) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getYList().hashCode();
      }
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
      hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getModelName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wt.TrainServing.TrainRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.TrainRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wt.TrainServing.TrainRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wt.TrainRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wt.TrainRequest)
        wt.TrainServing.TrainRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wt.TrainServing.internal_static_wt_TrainRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wt.TrainServing.internal_static_wt_TrainRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wt.TrainServing.TrainRequest.class, wt.TrainServing.TrainRequest.Builder.class);
      }

      // Construct using wt.TrainServing.TrainRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        batchSize_ = 0;

        modelName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wt.TrainServing.internal_static_wt_TrainRequest_descriptor;
      }

      @java.lang.Override
      public wt.TrainServing.TrainRequest getDefaultInstanceForType() {
        return wt.TrainServing.TrainRequest.getDefaultInstance();
      }

      @java.lang.Override
      public wt.TrainServing.TrainRequest build() {
        wt.TrainServing.TrainRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wt.TrainServing.TrainRequest buildPartial() {
        wt.TrainServing.TrainRequest result = new wt.TrainServing.TrainRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          x_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.x_ = x_;
        if (((bitField0_ & 0x00000002) != 0)) {
          y_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.y_ = y_;
        result.batchSize_ = batchSize_;
        result.modelName_ = modelName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wt.TrainServing.TrainRequest) {
          return mergeFrom((wt.TrainServing.TrainRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wt.TrainServing.TrainRequest other) {
        if (other == wt.TrainServing.TrainRequest.getDefaultInstance()) return this;
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        if (!other.y_.isEmpty()) {
          if (y_.isEmpty()) {
            y_ = other.y_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureYIsMutable();
            y_.addAll(other.y_);
          }
          onChanged();
        }
        if (other.getBatchSize() != 0) {
          setBatchSize(other.getBatchSize());
        }
        if (!other.getModelName().isEmpty()) {
          modelName_ = other.modelName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wt.TrainServing.TrainRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wt.TrainServing.TrainRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList x_ = emptyFloatList();
      private void ensureXIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          x_ = mutableCopy(x_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getXList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(x_) : x_;
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public float getX(int index) {
        return x_.getFloat(index);
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public Builder setX(
          int index, float value) {
        ensureXIsMutable();
        x_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public Builder addX(float value) {
        ensureXIsMutable();
        x_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       */
      public Builder clearX() {
        x_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList y_ = emptyFloatList();
      private void ensureYIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          y_ = mutableCopy(y_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getYList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(y_) : y_;
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public int getYCount() {
        return y_.size();
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public float getY(int index) {
        return y_.getFloat(index);
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public Builder setY(
          int index, float value) {
        ensureYIsMutable();
        y_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public Builder addY(float value) {
        ensureYIsMutable();
        y_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public Builder addAllY(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureYIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, y_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float y = 2;</code>
       */
      public Builder clearY() {
        y_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>int32 batch_size = 3;</code>
       */
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>int32 batch_size = 3;</code>
       */
      public Builder setBatchSize(int value) {
        
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batch_size = 3;</code>
       */
      public Builder clearBatchSize() {
        
        batchSize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modelName_ = "";
      /**
       * <code>string model_name = 4;</code>
       */
      public java.lang.String getModelName() {
        java.lang.Object ref = modelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          modelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getModelNameBytes() {
        java.lang.Object ref = modelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model_name = 4;</code>
       */
      public Builder setModelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model_name = 4;</code>
       */
      public Builder clearModelName() {
        
        modelName_ = getDefaultInstance().getModelName();
        onChanged();
        return this;
      }
      /**
       * <code>string model_name = 4;</code>
       */
      public Builder setModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modelName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wt.TrainRequest)
    }

    // @@protoc_insertion_point(class_scope:wt.TrainRequest)
    private static final wt.TrainServing.TrainRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wt.TrainServing.TrainRequest();
    }

    public static wt.TrainServing.TrainRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrainRequest>
        PARSER = new com.google.protobuf.AbstractParser<TrainRequest>() {
      @java.lang.Override
      public TrainRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrainRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrainRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wt.TrainServing.TrainRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wt.TrainReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float result = 1;</code>
     */
    java.util.List<java.lang.Float> getResultList();
    /**
     * <code>repeated float result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated float result = 1;</code>
     */
    float getResult(int index);
  }
  /**
   * Protobuf type {@code wt.TrainReply}
   */
  public  static final class TrainReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wt.TrainReply)
      TrainReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrainReply.newBuilder() to construct.
    private TrainReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrainReply() {
      result_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TrainReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrainReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                result_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                result_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                result_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          result_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wt.TrainServing.internal_static_wt_TrainReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wt.TrainServing.internal_static_wt_TrainReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wt.TrainServing.TrainReply.class, wt.TrainServing.TrainReply.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList result_;
    /**
     * <code>repeated float result = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getResultList() {
      return result_;
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated float result = 1;</code>
     */
    public float getResult(int index) {
      return result_.getFloat(index);
    }
    private int resultMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getResultList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(resultMemoizedSerializedSize);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeFloatNoTag(result_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getResultList().size();
        size += dataSize;
        if (!getResultList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        resultMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wt.TrainServing.TrainReply)) {
        return super.equals(obj);
      }
      wt.TrainServing.TrainReply other = (wt.TrainServing.TrainReply) obj;

      if (!getResultList()
          .equals(other.getResultList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wt.TrainServing.TrainReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wt.TrainServing.TrainReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.TrainReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wt.TrainServing.TrainReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wt.TrainServing.TrainReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wt.TrainReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wt.TrainReply)
        wt.TrainServing.TrainReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wt.TrainServing.internal_static_wt_TrainReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wt.TrainServing.internal_static_wt_TrainReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wt.TrainServing.TrainReply.class, wt.TrainServing.TrainReply.Builder.class);
      }

      // Construct using wt.TrainServing.TrainReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wt.TrainServing.internal_static_wt_TrainReply_descriptor;
      }

      @java.lang.Override
      public wt.TrainServing.TrainReply getDefaultInstanceForType() {
        return wt.TrainServing.TrainReply.getDefaultInstance();
      }

      @java.lang.Override
      public wt.TrainServing.TrainReply build() {
        wt.TrainServing.TrainReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wt.TrainServing.TrainReply buildPartial() {
        wt.TrainServing.TrainReply result = new wt.TrainServing.TrainReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          result_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wt.TrainServing.TrainReply) {
          return mergeFrom((wt.TrainServing.TrainReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wt.TrainServing.TrainReply other) {
        if (other == wt.TrainServing.TrainReply.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wt.TrainServing.TrainReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wt.TrainServing.TrainReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList result_ = emptyFloatList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          result_ = mutableCopy(result_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getResultList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(result_) : result_;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public int getResultCount() {
        return result_.size();
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public float getResult(int index) {
        return result_.getFloat(index);
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder setResult(
          int index, float value) {
        ensureResultIsMutable();
        result_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addResult(float value) {
        ensureResultIsMutable();
        result_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float result = 1;</code>
       */
      public Builder clearResult() {
        result_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wt.TrainReply)
    }

    // @@protoc_insertion_point(class_scope:wt.TrainReply)
    private static final wt.TrainServing.TrainReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wt.TrainServing.TrainReply();
    }

    public static wt.TrainServing.TrainReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrainReply>
        PARSER = new com.google.protobuf.AbstractParser<TrainReply>() {
      @java.lang.Override
      public TrainReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrainReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrainReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wt.TrainServing.TrainReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wt_PredictRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wt_PredictRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wt_PredictReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wt_PredictReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wt_TrainRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wt_TrainRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wt_TrainReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wt_TrainReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023train_serving.proto\022\002wt\"J\n\016PredictRequ" +
      "est\022\017\n\007feature\030\001 \003(\002\022\023\n\013sample_size\030\002 \001(" +
      "\005\022\022\n\nmodel_name\030\003 \001(\t\"\036\n\014PredictReply\022\016\n" +
      "\006result\030\001 \003(\002\"L\n\014TrainRequest\022\t\n\001x\030\001 \003(\002" +
      "\022\t\n\001y\030\002 \003(\002\022\022\n\nbatch_size\030\003 \001(\005\022\022\n\nmodel" +
      "_name\030\004 \001(\t\"\034\n\nTrainReply\022\016\n\006result\030\001 \003(" +
      "\0022g\n\004Caca\022/\n\005score\022\022.wt.PredictRequest\032\020" +
      ".wt.PredictReply\"\000\022.\n\010training\022\020.wt.Trai" +
      "nRequest\032\016.wt.TrainReply\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wt_PredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wt_PredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wt_PredictRequest_descriptor,
        new java.lang.String[] { "Feature", "SampleSize", "ModelName", });
    internal_static_wt_PredictReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wt_PredictReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wt_PredictReply_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_wt_TrainRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wt_TrainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wt_TrainRequest_descriptor,
        new java.lang.String[] { "X", "Y", "BatchSize", "ModelName", });
    internal_static_wt_TrainReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wt_TrainReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wt_TrainReply_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
